name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # Заменить
          username: ${{ secrets.SSH_USERNAME }}  # Заменить 
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Заменить
          script: |
              composer --v
