name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: 188.120.238.80
          username: root
          key: ${{secrets.PIXINVENT_KEY}}
          target: /var/www/html
          source: ./*

      - name: Execute commands on remote server
        uses: appleboy/ssh-action@master 
        with:
          host: 188.120.238.80
          username: root
          key: ${{secrets.PIXINVENT_KEY}}
          script: |
                echo "Current user: $(whoami)"
                echo "Current directory: $(pwd)"
                cd /var/www/html || exit 1
                git config --global --add safe.directory /var/www/html
                git pull
                echo "Current directory: $(pwd)"
                chown -R www-data:www-data /var/www/html/storage
                mysql -u root -p'root' -e "CREATE DATABASE IF NOT EXISTS laravel;"
                export COMPOSER_ALLOW_SUPERUSER=1
                composer update
                cp .env.example .env
                php artisan key:generate
                php artisan migrate:fresh --seed
                export NODE_OPTIONS=--max-old-space-size=4096
                bun install --legacy-peer-deps
                bun run build
                ls -la
